### ISSUE TITLE
querry

### ISSUE THREAD

**Issue by aj07** [libp2p/specs#112]
I am working on some P2P idea and reading lot on Libp2p as well as Kaledmia Protocol.  Is there any community call or can have conf call to understand more whether Libp2p can be used for our usecase or not ?

**Comment by mxinden** [comment]
Hi @aj07, sorry for never replying here. Describing your use case in discuss.libp2p.io/ is likely the best way forward.

I am closing here. Please follow up in discuss.libp2p.io/ for any usage questions and here for any specification questions.
