### ISSUE TITLE
Gossipsub: Return for Graft

### ISSUE THREAD

**Issue by jamesray1** [libp2p/specs#113]
> On `GRAFT(topic)` it adds the peer to `mesh[topic]` if it is subscribed to the topic. If it is not subscribed, it responds with a `PRUNE(topic)` control message.

Similarly to the code in rust-libp2p with subscribe and unsubscribe (see below), it seems to make more sense to simply return false for grafting if it is not subscribed, and return true on success.

https://github.com/libp2p/rust-libp2p/blob/83320e0347e1feff80ebadcdf25ad9376e176164/protocols/floodsub/src/layer.rs#L75-L78:

```rust
    /// Subscribes to a topic.
    ///
    /// Returns true if the subscription worked. Returns false if we were already subscribed.
pub fn subscribe(&mut self, topic: Topic) -> bool {
```
https://github.com/libp2p/rust-libp2p/blob/83320e0347e1feff80ebadcdf25ad9376e176164/protocols/floodsub/src/layer.rs#L100-L105:
```rust
    /// Unsubscribes from a topic.
    ///
    /// Note that this only requires a `TopicHash` and not a full `Topic`.
    ///
    /// Returns true if we were subscribed to this topic.
pub fn unsubscribe(&mut self, topic: impl AsRef<TopicHash>) -> bool {
```

Context: implementing gossipsub for Rust at https://github.com/libp2p/rust-libp2p/pull/767.

Cc @vyzo.

**Comment by vyzo** [comment]
Not sure what you mean by simply returning on a rejected GRAFT; the PRUNE must be emitted, otherwise the peer will be in the GRAFTing peer's mesh table.

**Comment by jamesray1** [comment]
But won't it only be in the grafting peers mesh table after the graft is successfully completed and if the peer is subscribed to the topic?

**Comment by vyzo** [comment]
If it doesn't graft, it should emit a `PRUNE` to notify the originating peer to drop the link (because it has already grafted).

**Comment by vyzo** [comment]
right, we don't use a 3-way handshake; we add link and send GRAFT, and if the peer wants to reject us it sends a PRUNE.

**Comment by mxinden** [comment]
I am closing here given that the last response seem to have answered the initial question and due to lack of progress. Please re-open or comment in case you would like to resume the discussion.
