### ISSUE TITLE
Question: After a `JOIN`/`LEAVE` to a topic should the peer emit a `SUBSCRIBE`/`UNSUBSCRIBE`? 

### ISSUE THREAD

**Issue by AgeManning** [libp2p/specs#121]
I've been reading the spec and noticed the line: 

> Also note that as part of the pubsub api, the peer emits `SUBSCRIBE` and `UNSUBSCRIBE` control messages to all its peers whenever it joins or leaves a topic.

After briefly looking at the go-implementation, these messages don't seem to be explicitly sent in the join/leave functions. 
See the `Leave` function for example: 
https://github.com/libp2p/go-libp2p-pubsub/blob/2e1fb613f98d27ecc07f3800137daeab45ddb02e/gossipsub.go#L287

It sends a `PRUNE` to all peers in it's mesh. Should it also send `UNSUBSCRIBE` to all peers? Or have I misunderstood or missed something?

Is it the case that when a peer unsubscribes, it sends the `UNSUBSCRIBE` to all peers and then calls `Leave`?

**Comment by vyzo** [comment]
they are emitted by the baseline pubsub:
- https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L406
- https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L384

**Comment by AgeManning** [comment]
Yep, thanks for the direction. 

After looking more carefully at it - `handleRemoveSubscription` is called from a channel which emits the `UNSUBSCRIBE` message before calling the router's `Leave` function.
