### ISSUE TITLE
Topology in use in Gossipsub

### ISSUE THREAD

**Issue by Mikerah** [libp2p/specs#122]
I am trying to get a deeper understanding of gossipsub. Currently, the specification for gossipsub gives little details about what the network topology is. 

This is what I have in mind about the network topology of gossipsub:
    - In the meshsub step, the local topology is a strongly-connected tournament, where the in-degree = out-degree <= D
    - To stabilize the mesh, peers get removed (pruned) and the mesh turns into a tree/line topology.
So, the network topology of gossipsub is a line/tree topology.

Is this correct? If not, I would like to get an understanding of the topology structure of gossipsub.

**Comment by vyzo** [comment]
The topology is a strongly connected mesh with in-degree = out-degree =~ D (approximately D).
The pruning step doesn't produce a tree/line, it keeps the mesh; the intention is to stabilize the overlay and bring the degree down to D.

**Comment by Mikerah** [comment]
Thank you for the clarification.
