### ISSUE TITLE
Clarification for the ambient peer discovery section of the gossipsub spec

### ISSUE THREAD

**Issue by Mikerah** [libp2p/specs#125]
At the beginning of the ambient peer discovery section, it starts with 

> With ambient peer discovery, the function is pushed outside the scope of the protocol. 

Is this meant to say that floodsub doesn't depend on a particular method of peer discovery, e.g. a DHT, but depends on peers themselves to announce themselves to other peers. Then, the protocol will check if that peer is running floodsub or gossipsub and responds accordingly? Not really sure what function is pushed outside the scope of the protocol is suppose to mean.

**Comment by raulk** [comment]
It's a rather cryptic way of saying that finding pubsub peers is a _passive_ action, that relies on the discovery mechanism that the libp2p node is using. This can be peer routing via DHT, rendezvous, local discovery, etc.

go-libp2p-pubsub [registers a notifee](https://github.com/libp2p/go-libp2p-pubsub/blob/master/notify.go#L18) with the libp2p stack and reacts to new connections being made [by opening a stream](https://github.com/libp2p/go-libp2p-pubsub/blob/master/comm.go#L59) for the currently supported pubsub routing protocol IDs (gossipsub, floodsub).

If the other party ACKs the protocol negotiation, we know we have found a pubsub peer and we add them to the overlay.

**Comment by raulk** [comment]
@Mikerah does that help?

**Comment by Mikerah** [comment]
@raulk, yes it does. Thanks
