### ISSUE TITLE
Clarification in emitting gossip - Gossipsub

### ISSUE THREAD

**Issue by AgeManning** [libp2p/specs#129]
Just wanted to verify a small discrepancy I noticed in the spec compared to the go-implementation. 
The spec states that gossip is emitted to peers that not part of the mesh like so:
```
for each topic in mesh+fanout:
  let mids be mcache.window[topic]
  if mids is not empty:
    select D peers from peers.gossipsub[topic]
    for each peer not in mesh[topic]
      emit IHAVE(mids)

shift the mcache
```
In the go implementation (see these two lines): 
https://github.com/libp2p/go-libp2p-pubsub/blob/d4589956d289b383aa66807840b5baa3f6916f9f/gossipsub.go#L428
https://github.com/libp2p/go-libp2p-pubsub/blob/d4589956d289b383aa66807840b5baa3f6916f9f/gossipsub.go#L464
Peers are chosen such that they are not in the mesh (the first line), then peers are chosen such that they are not in the fanout (second line). 

Should the spec read?: 

for each topic in mesh+fanout:
  let mids be mcache.window[topic]
  if mids is not empty:
    select D peers from peers.gossipsub[topic]
    for each peer not in mesh[topic] or **fanout[topic]**
      emit IHAVE(mids)

shift the mcache

**Comment by vyzo** [comment]
yes indeed.
