### ISSUE TITLE
gossipsub: i_want could also return the requested messages that are not in the mcache

### ISSUE THREAD

**Issue by jamesray1** [libp2p/specs#130]
The gossipsub spec says that the i_want function "requests transmission of messages announced in an IHAVE message" and "forwards all request messages that are present in mcache to the
requesting peer." I think it might be helpful for convenience to also return the message hashes/IDs that were not present in the mcache.

**Comment by jamesray1** [comment]
Note that I have implemented conversion of message hashes back into messages, which would be useful here since we could not only return the not found message hashes, but the messages associated with them, or just return all of the messages via reconstructing from the hashes, whether they are in the cache or not. There may be privacy issues with doing that, however.

**Comment by vyzo** [comment]
It's meaningless to return message IDs not in the mcache, as we wont be able to retransmit this messages.

**Comment by mxinden** [comment]
I am closing here as the discussion stalled / resolved with the most recent comment. Please follow up here in case you would like to continue the discussion.
