### ISSUE TITLE
Importance of implementing Control Message Piggybacking

### ISSUE THREAD

**Issue by Mikerah** [libp2p/specs#134]
In the current GossipSub specification, there are details lacking for the `Control Message Piggybacking` section. In fact, it is advised that we look at the reference Go implementation for more details. The way that section is currently written implies, to me at least, that implementing control message piggybacking is optional to making GossipSub work. However, in the Go implementation, it seems has been implemented in such a way that it relies on control message piggybacking.

How important is it that implementers implement control message piggybacking in their GossipSub implementations? If it is indeed important to implement, it needs to be properly specified, so that we don't need to rely as much on the Go implementation. If it is not important, then we, as implementers, need to know if we should implement in our GossipSub implementation.

**Comment by vyzo** [comment]
It really is optional, the protocol ought to work just fine without piggybacking.
On the same time it's nice to have: it provides control packet cost amortization if you have peers sharing multiple topics.

**Comment by mxinden** [comment]
Closing here as control message piggybacking is optional. Pull requests extending the specification to make this more clear are as always more than welcome.
