### ISSUE TITLE
pubsub: authentication and immutability

### ISSUE THREAD

**Issue by connectdotz** [libp2p/specs#135]
In theory, when a subscriber receives a message, the system should ensure the following integrity: 
- the message is indeed from the sender ("from") (authentication)
- the message (data + from) hasn't been tampered (immutability)

Reading the [spec](https://github.com/libp2p/specs/tree/master/pubsub), I am not sure how it expects to deliver such promises in practice, where not all users have their own node, and not all nodes are honest... :

# authentication
there is an `AuthMode 'KEY'` that looked promising,  but the publish API didn't allow us to specify a key, which means the node is probably using its default peerID, how will this work in a multi-user node, such as a gateway? What stops a faulty node from using other's peerID in the "from" field?

# immutability
with or without relay, how do the subscribers know the messages they received have not been tampered, either the "from" or the "data"?

Maybe the spec left out some detail? one would think if the publisher requires to sign each message + the node to validated upon both pub() and sub(), it should be able to address both problems... I could be wrong, doesn't IPNS records deploy a similar scheme? Maybe libp2p expect such integrity to be enforced in higher (app) stack? Although I argue these issues are pretty fundamental/common thus valuable to be provided by libp2p...

**Comment by vyzo** [comment]
We have already implemented message signing in go, which provides both authentication and immutability.
It needs to be spec'ed though.

**Comment by connectdotz** [comment]
> We have already implemented message signing in go, which provides both authentication and immutability.

that's great! however, I didn't see the js implementation follow suit, which makes me wonder what's the relationship between the spec and the implementation... i.e. do we always experiment new ideas in impl first then retrofit to spec then sync across other impl packages? (BTW, IPFS community is great, but there are lots of spec/impl/notes packages and sometimes it is difficult to know where to look for the defacto spec, asking questions or filing issues/requests...)

---

Another point that I should have called out explicitly in the original post -- **authorization**: _can this user publish/subscribe to this topic?_ 

Yes, signature you mentioned does satisfy authentication and immutability from a node, but I am afraid it is insufficient regarding authorization for node-less clients...

today the message (or IPNS name) is signed by the node (looks like IPFS/libp2p assumed the key-management/signing is always done in the node)... it is fine if user to node is "1-to-1" or even "1-to-many"; but for a client-only configuration (such as [js-ipfs-http-client](https://github.com/ipfs/js-ipfs-http-client)), i.e. "many-to-1" or "many-to-many", which a user can publish messages through any remote node, and a node can publish messages on behave of many different users: how do we check authorization if we can't get the actual user signature/pk...?

I have seen a similar design in early ethereum, but later on, they added the ability like local-sign, local-key-management for client-only apps (connecting to remove node via https for example). We could certainly implement this in our own messaging stack on top of libp2p, but again seems like libp2p can easily accomplish this common feature by allowing a pass-through signature/pk?

**Comment by vyzo** [comment]
> that's great! however, I didn't see the js implementation follow suit, which makes me wonder what's the relationship between the spec and the implementation... i.e. do we always experiment new ideas in impl first then retrofit to spec then sync across other impl packages?

Sometimes the spec preceeds, but it's usually implementation first, spec later.

> authorization: can this user publish/subscribe to this topic?

We have validators in `go-libp2p-pubsub` which can serve the function with user-specific criteria.

**Comment by vyzo** [comment]
> it is insufficient regarding authorization for node-less clients...

They must still have a key, and the message signing is implemented in a way that embeds the public key in the message. So there shouldn't be any blockers as far as the protocol is concerned.

**Comment by connectdotz** [comment]
hmmm... from the [go-libp2p-pubsub](https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L834):

func (*PubSub) Publish:
```
func (p *PubSub) Publish(topic string, data []byte) error
```

This matches the [interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/PUBSUB.md#pubsubpublish), so I assume it is the API client should use, which does not take any option for signature/pk/message... 

I do see you can pass message around in [subRouter](https://godoc.org/github.com/libp2p/go-libp2p-pubsub)  APIs, are you suggesting the client should use these APIs directly? I am not sure they are the right entry points as they kind of exposed the internal message format and the seqno...

**Comment by vyzo** [comment]
There is no API for publishing already signed and prepared messages currently -- what I was alluding to is that it can be done at the protocol level.

**Comment by connectdotz** [comment]
got it.

I wouldn't mind adding these API and other security measurements, such as subscription security, with the goal to make p2p pubsub to be truly secured (and private) for more use cases... since our platform is js, I am thinking to start from the js front, what is the best way to discuss/validate these changes with the community (especially go and js libp2p-pubsub developers) prior to submitting a PR ?

**Comment by vyzo** [comment]
We can discuss it here.

**Comment by connectdotz** [comment]
> We can discuss it here.

😄 

ok, here is the high-level list I am interested in contributing to js-libp2p-pubsub (maybe in a few PRs),  and hopefully integrated to spec and go packages later:
- [ ] add signature/key to js message format (data structure, parity)
- [ ] add `options` parameter to take {signature,key} for `publish()` and `subscribe()`. If options is null, default to use the current ID so it's backward compatible. (support node-less clients)
  - [ ] populate new message with signature/key  if not provided by caller. (parity)
- [ ] add key/signature validation for `publish()` and `subscribe()` when key != myID. (authentication)
  - [ ] what should a `subscribe()` sign? maybe its own key ?
- [ ] extend AuthMode.KEY to allow authorization on `subscribe()` as well
  - [ ] add  {sub-keys, pub-keys} to allow fine-grained control on both ends.  (authorization)

Follwoing are not security/auth related, but nevertheless commonly needed:

- [ ] add a new API to  `replay()` all the cached messages for a given topic to allow subscrbers to _catchup_.
  - [ ] there might need to be more discussion, as the node doesn't guarantee full history of messages nor the order, do we need to connect to multiple peers and compare? or just best-effort?
- [ ] add TTL for a given topic or message, to help reduce cache size and improve security.
  - [ ] we could follow IPNS TTL style

cc @vasco-santos to get his perspective as well.

**Comment by connectdotz** [comment]
ok, will do.

**Comment by mxinden** [comment]
I am closing here as https://github.com/libp2p/specs/pull/140/ addresses the main concern (authentication). Feel free to comment again in case you would like to continue on authorization.
