### ISSUE TITLE
Clarification in description of topic membership

### ISSUE THREAD

**Issue by Mikerah** [libp2p/specs#136]
In the current description of when a router joins a topic

> On `JOIN(topic)` the router joins the topic. In order to do so, if it already has `D` peers from the fanout peers of a topic, then it adds them to `mesh[topic]`, and notifies them with a `GRAFT(topic)` control message. Otherwise, if there are less than `D` peers (let this number be `x`) in the fanout for a topic (or the topic is not in the fanout), then it still adds them as above (if there are any), and selects the remaining number of peers `(D-x)` from `peers.gossipsub[topic]`, and likewise adds them to `mesh[topic]` and notifies them with a `GRAFT(topic)` control message.

If we break this down, we have 2 cases:

- If the router contains `D` peers that are subscribed to a topic that are not in `mesh[topic]` i.e. they are in `fanout[topic]`

- If the router contains less than `D` peers that are subscribed to a topic that are in `fanout[topic]`

From the description that I copied over, it seems like the main difference in both cases is that in the second case, we are sampling from the `D-x` peers of `peers.gossipsub[topic]` and adding them to `mesh[topic]` in addition to adding the `x` peers of `fanout[topic]` (regardless of which protocol they are using) to `mesh[topic]`. Is this right? The second portion of the paragraph is unclear about this.

In the [reference implementation](https://github.com/libp2p/go-libp2p-pubsub/blob/master/gossipsub.go#L270), it seems like an optimization was done since both cases are very similar. Is this right?

**Comment by vyzo** [comment]
Yes, the reference implementation does it lazily.

To elaborate:
The whole point is to get to D peers, using your existing fanout peers (if any).
If you have less than D peers in the fanout, then select the rest from the peer list.
In the reference implementation, the case of `0 < |fanout| < D` is handled lazily: it adds the fanout peers to the mesh and adds the remaining peers lazily in the heartbeat.

**Comment by vyzo** [comment]
Also, it's not regardless of protocol they are using: floodsub peers are never added to the mesh, only gossipsub peers.

**Comment by mxinden** [comment]
Closing here as question seems to be answered.
