### ISSUE TITLE
One 'relay spec' to rule them all

### ISSUE THREAD

**Issue by diasdavid** [libp2p/specs#14]
In an attempt to converge all the relay spec notes and discussions, I'm listing them here, so that they can all be considered for the revamp of the relay spec. (Order represents the timeline of how theses appear, last should be considered as last 'discussed')

- first iteration of the spec - https://github.com/libp2p/specs/blob/master/relay/README.md
- question: wire protocol message format - https://github.com/libp2p/specs/issues/12
- question: relay vs tunnel - https://github.com/libp2p/specs/pull/8
- implementation notes - https://github.com/libp2p/js-libp2p-circuit/blob/master/implementation-notes.md
- Why's concerns about current implementation - https://github.com/libp2p/js-libp2p-circuit/issues/8
- Relay use cases - https://github.com/libp2p/js-libp2p-circuit/issues/6
- moar notes - https://github.com/libp2p/js-libp2p-circuit/issues/2
- moar discussion - https://github.com/libp2p/js-libp2p-circuit/issues/4
- errors table: https://gist.github.com/whyrusleeping/7665164d04e43171e6cb7b8aa6205645#file-errors-md
- wire protocol: https://gist.github.com/whyrusleeping/7665164d04e43171e6cb7b8aa6205645#file-relay-md

**Comment by dryajov** [comment]
Thanks for compiling this! @diasdavid

**Comment by diasdavid** [comment]
-> https://github.com/libp2p/specs/pull/15
