### ISSUE TITLE
Differing implementation of gossipsub that handles errors and uses hashes of messages and topics instead of IDs

### ISSUE THREAD

**Issue by jamesray1** [libp2p/specs#142]
[This is a partial implementation of gossipsub](https://github.com/libp2p/rust-libp2p/pull/767) that differs to the spec by handling errors and using hashes of messages and topics instead of IDs. While it is possible to use an enum containing either a hash or an ID, after trying to implement that I stopped due to additonal complexities around doing so, while there does not seem to be any advantage to using an ID over a hash.

Handled errors include when a topic is not in the mesh, and the local peer is not connected to the remote peer.
Relevant lines in the spec include:
- https://github.com/libp2p/rust-libp2p/pull/767/files#diff-c0f248eeadd1b209ed0f7a48476b360fR44-76
- Also CTRL+F `graft_errs` and `prune_errs` in layer.

Related: #130, #116

**Comment by raulk** [comment]
Thanks for the info, but this is not actionable. Implementors are welcome to submit RFCs to evolve the spec when they find areas for improvement.
