### ISSUE TITLE
pubsub: validator functions are not specified

### ISSUE THREAD

**Issue by raulk** [libp2p/specs#146]
A quick find did not return results for validator functions in the pubsub or gossipsub specs. This is a functionality of pubsub should be, IMO, spec'ed out as it affects message propagation through the network.

**Comment by vyzo** [comment]
validator functions are an implementation detail, not a protocol aspect...

**Comment by raulk** [comment]
The protocol aspect is just one element of a spec. Specs have to specify behaviours as well, and in general any feature that we want spec implementors to follow. See the HTTP spec for a good example of this.

**Comment by vyzo** [comment]
yes, but there is nothing to specify! It's just an api with application-level semantics.

**Comment by raulk** [comment]
@vyzo take into account that for a person foreign to gossipsub, there is no indication this feature even exists, what it is expected to do, what guarantees it offers, what is the input, what is the output, how it can error, etc.

I’ll come up with a wording soon.
