### ISSUE TITLE
Specifications for SECIO

### ISSUE THREAD

**Issue by Mikerah** [libp2p/specs#152]
I am currently going through the p2p stack we need for our client. I am trying to understand what SECIO is used for and what its specification is. It seems like it what a replacement for TLS encryption but there aren't many details.

Are there plans to write a specification for SECIO?

**Comment by marten-seemann** [comment]
The spec currently lives in this PR: https://github.com/libp2p/specs/pull/106
We'll probably soon replace it by TLS though: https://github.com/libp2p/specs/pull/151

**Comment by Mikerah** [comment]
Are there plans to use both SECIO and TLS or have the option to decide which encryption protocol to use?

**Comment by marten-seemann** [comment]
You can use both for now (once we add TLS support), but we might deprecate secio at some point.

**Comment by Mikerah** [comment]
Thank you for the quick replies.
