### ISSUE TITLE
User Topic Validation

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/specs#167]
Some questions that came up talking to @anorth about [PubSub Topic Validation](https://github.com/libp2p/specs/tree/master/pubsub#topic-validation):

1.  In general, what guarantees are made and to whom?  For instance, will a subscriber ever receive an invalid (e.g., malformed) inbound messages?
2.  Is the same validation done on inbound & outbound?  Ditto for locally generated versus rebroadcast messages?

cc @yusefnapora @vyzo

**Comment by Stebalien** [comment]
All messages are validated before they're sent, forwarded, and/or delivered to the local application (unless there's a bug).

**Comment by anorth** [comment]
That's good to know. Adding that sentence to the spec would help clarify.

**Comment by mxinden** [comment]
> When propagating a message for a topic, implementations will invoke all validators attached to that topic, and will only continue propagation if, and only if all, validations pass.

> Local handling of failed validation is left up to the implementation (e.g. logging).

With the two excerpts in the specification above, I would deem this issue as resolved. Please comment here in case you would like to see additional clarification in the specification.
