### ISSUE TITLE
Spec reviews should have a guaranteed minimum review period

### ISSUE THREAD

**Issue by lanzafame** [libp2p/specs#170]
Reasoning outlined [here](https://github.com/libp2p/specs/pull/169#issuecomment-495426612).

I am not sure what the best timeframe is but I think that a week would be a good start for the minimum timeframe a spec should be open for review before potentially merging based on the consensus of those that have commented. Said another way, even if consensus is reached, the spec review should remain open for a week.

**Comment by raulk** [comment]
Not sure I follow. The process already defines a 5 working day period for initial working drafts (short on purpose to allow quicker entry into incubation) and 10 working days for Candidate Recommendations and Recommendations.

Is there something else that needs to be added now, or is this issue addressing the one-off event on merging the meta-spec (which we discussed in that issue)?

**Comment by raulk** [comment]
(And the phrasing specifically goes: “allowing X days to elapse to collect feedback from the libp2p community at large”.) I believe this addresses your concerns, in which let’s close the issue.

**Comment by lanzafame** [comment]
@raulk Ahh I was just confused as to why a similar timeframe wasn't applied to the meta-spec? I am happy to close.
