### ISSUE TITLE
Add spec for AutoNAT

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/specs#180]
The [AutoNAT service](https://github.com/libp2p/go-libp2p-autonat-svc) doesn't have a spec yet, so we should write one :) We should also spec out the client side of AutoNAT as well, and perhaps speak to how it fits in with the AutoRelay feature.

@jacobheun has started looking into the js implementation - if you come up with any useful notes drop them in this issue please!

**Comment by jacobheun** [comment]
I'll take this on. I got a bit consumed by some recent events, but should be able to put a draft together of the spec soon.

**Comment by yusefnapora** [comment]
Sweet, thanks Jacob 💯

**Comment by mxinden** [comment]
> I'll take this on. I got a bit consumed by some recent events, but should be able to put a draft together of the spec soon.

@jacobheun I am guessing that you are no longer working on this? If so, could you un-assign yourself?

**Comment by jacobheun** [comment]
@mxinden that's correct, updated.
