### ISSUE TITLE
Add spec for ping protocol

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/specs#183]
This isn't the highest priority, but we ought to spec out the ping protocol to be thorough.

If / when we want to standardize the spec format (#160), this would make a decent venue for bikeshedding our way towards a consistent style, since there's not likely to be a ton of content to get in the way 😄

**Comment by muddlebee** [comment]
hey @yusefnapora  anyone working on this yet? I was looking for the `PING` specs . I couldn't find any :( 

https://docs.rs/libp2p-ping/latest/src/libp2p_ping/lib.rs.html#21

**Comment by mxinden** [comment]
None that I am aware of unfortunately. Would you want to contribute one @muddlebee? I am happy to help along the way.

**Comment by tomaka** [comment]
While the protocol itself is very simple, an important thing to be specified is whether the substream stays open between pings or not.

**Comment by thomaseizinger** [comment]
This has been resolved, can somebody close this?
