### ISSUE TITLE
SECIO: Protobuf Propose.pubkey can be defined as crypto.pb.PublicKey

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/specs#193]
The protobuf `Propose.pubkey` is defined as `bytes` while it is serialized protobuf `crypto.pb.PublicKey` message. 
It could be defined in the following way for better clarity: 
```proto
import "crypto.proto";

message Propose {
	optional bytes rand = 1;
	optional crypto.pb.PublicKey pubkey = 2;
	optional string exchanges = 3;
	optional string ciphers = 4;
	optional string hashes = 5;
}
```

**Comment by Stebalien** [comment]
Note: this would _not_ change the wire format (i.e., it's backwards compatible) as embedded messages have the same wire type as bites.

**Comment by mxinden** [comment]
Closing here as SECIO has been deprecated (see https://github.com/libp2p/specs/pull/308).
