### ISSUE TITLE
Be explicit about use of protobuf version 2

### ISSUE THREAD

**Issue by oskarth** [libp2p/specs#281]
## Problem

Protobuf2 and 3 are different protocols with different semantics. From reading the specs, it is not obvious which version is used. The same is true looking at the docs site https://docs.libp2p.io/concepts/protocols/

Looking at e.g. https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/pb/identify.proto#L1 one can infer that protobuf2 is used.

## Potential solutions

1. Docs site should be explicit about use of protobuf2 unless otherwise mentioned
2. It could be mentioned in the beginning of each spec
3. It could be mentioned in a meta spec (e.g. lifecycle document, or style guide)
4. `syntax = "proto2";` could be added to every protobuf field in line

As an example, at Status we specify `proto3` in the main spec once: https://specs.status.im/spec/1#protobuf

## Notes and related links

- https://github.com/status-im/nim-protobuf-serialization/issues/4
- https://developers.google.com/protocol-buffers/docs/proto?hl=en#optional
- https://developers.google.com/protocol-buffers/docs/proto3?hl=en#default

**Comment by sinkingsugar** [comment]
I'd like to point out also that 2 implementations of the `noise` spec are using `proto3`
Not strictly connected to this issue but to not forget, keep track and investigate.

* go: https://github.com/libp2p/go-libp2p-noise/blob/master/pb/payload.proto#L1
* rust: https://github.com/libp2p/rust-libp2p/blob/cc3438ec378c653cbfda9f73585687bdad45a92f/protocols/noise/src/io/handshake/payload.proto#L1

**Comment by oskarth** [comment]
Closed in https://github.com/libp2p/specs/pull/282
