### ISSUE TITLE
connections/README.md: Missing link

### ISSUE THREAD

**Issue by prataprc** [libp2p/specs#297]
In the [Future works][future-works] section under connections/README.md

> There is also [a proposal][resource-manager-issue] for a more comprehensive resource management system, which woul

Where to find the proposal ?

Cheers,

[future-works]: https://github.com/prataprc/specs/tree/master/connections#future-work

**Comment by mxinden** [comment]
Thanks @prataprc for raising the issue. https://github.com/libp2p/specs/pull/311 fixes it.
