### ISSUE TITLE
relay: STOP_RELAY_REFUSED error code

### ISSUE THREAD

**Issue by vyzo** [libp2p/specs#30]
As discussed with @dryajov, we need an error code to distinguish internal stop errors, ike timeouts when accepting the new stream.
I propose a general error code for these cases, STOP_RELAY_REFUSED.

**Comment by vyzo** [comment]
We also need an error code to handle errors detected by the hop in the protocol handshake. This error code is suitable for this usage as well.

**Comment by dryajov** [comment]
This is being handled in PR - https://github.com/libp2p/specs/pull/24

**Comment by dryajov** [comment]
@vyzo can you document what both this messages do please? 
`MALFORMED_MESSAGE` is self explanatory, but I'm not sure about `STOP_RELAY_REFUSED` what are the conditions you seek to handle with it?

**Comment by vyzo** [comment]
Sure, will do directly in the PR.

**Comment by vyzo** [comment]
Documented in https://github.com/libp2p/specs/pull/24/commits/d131ea6436d30fe91c388d2a65974a2f2c2d25d9

**Comment by mxinden** [comment]
As far as I can tell, the two concerns (STOP_RELAY_REFUSED and MALFORMED_MESSAGE) are both addressed, thus closing. Feel free to reopen.
