### ISSUE TITLE
Gossipsub: protobuf type of signedPeerRecord

### ISSUE THREAD

**Issue by blacktemplar** [libp2p/specs#300]
Is there any specific reason why the type of a `signedPeerRecord` in the protobuf message type `PeerInfo` (https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#protobuf) is `bytes` and not the protobuf message type `Envelope` defined in the specs https://github.com/libp2p/specs/blob/rfc/address-records/RFC/0002-signed-envelopes.md#wire-format?

**Comment by mxinden** [comment]
@vyzo do you know an answer here as a GossipSub expert?

**Comment by vyzo** [comment]
we wanted to avoid the dependency between protobufs and a fixed payload;
the PX extension was implemented before the envelope spec was finalized.

**Comment by mxinden** [comment]
Thanks @vyzo.

Closing here since the above answers the question. @blacktemplar please follow up with another comment in case you would like to continue the discussion.
