### ISSUE TITLE
PeerId spec mandates supporting RSA

### ISSUE THREAD

**Issue by dvc94ch** [libp2p/specs#313]
Can the spec be loosened to making RSA optional? It is not clear why there is such a wild zoo of supported identity algorithms, what amount of usage they have. Personally I think algorithms other than ed25519 should probably be deprecated at some point, since I don't see a good justification for supporting them.

**Comment by Stebalien** [comment]
Fair enough. Implementations SHOULD support RSA if they want to interoperate with IPFS nodes, but there's really no reason to require it. I've left the requirement for Ed25519 so there's _some_ "standard" key format, but that should be enough.
