### ISSUE TITLE
The lifecycle document is not followed very strictly

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/specs#336]
This issue is not a criticism but more of an observation :)

I just read through the lifecycle document again and noticed that - according to that - any spec that stays in `Working Draft` for longer than 4 months without being extended is supposed to move into [`Terminated`](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md#terminated). To avoid this, it shall be pushed forward towards a `Candidate Recommendation`.

Neither of this has happened with the [rendezvous](https://github.com/libp2p/specs/tree/master/rendezvous) protocol. I don't see an immediate need to change this, just wanted to get a feeling for how this is usually handled. I hope this doesn't trigger a PR now where the spec is being terminated because we are [on the pathway](https://github.com/libp2p/rust-libp2p/pull/2107) of using it :)

**Comment by mxinden** [comment]
> The lifecycle document is not followed very strictly

Correct. I hope to either (a) loosen the lifecycle document or (b) make the specifications follow the document more strictly in the future. That said, this is a rather large effort and likely not going to happen any time soon.

> To avoid this, it shall be pushed forward towards a Candidate Recommendation.

I am fine with promoting the Rendezvous specification to _Candidate Recommendation_, though, given my low involvement, my vote should be given little weight.

@vyzo @vasco-santos what is your opinion?

> I hope this doesn't trigger a PR now where the spec is being terminated because we are on the pathway of using it :)

:D I don't think we should remove the Rendezvous protocol.

**Comment by vyzo** [comment]
if the implementations are merged and tested interoperable, we can move to
CR.

**Comment by thomaseizinger** [comment]
> Correct. I hope to either (a) loosen the lifecycle document or (b) make the specifications follow the document more strictly in the future. That said, this is a rather large effort and likely not going to happen any time soon.

Thanks for the clarification.
I primarily opened this issue to have the question answered. Closing this issue as a result.
