### ISSUE TITLE
Question about peer-routing vs discovery

### ISSUE THREAD

**Issue by ghost** [libp2p/specs#36]
I'm a bit confused about what the difference is between the peer-routing and discovery interfaces.
Could you elaborate on the specific functions that each interface provides, or some reading material that provides some context for the interfaces?

Thanks

**Comment by lgierth** [comment]
Discovery is about finding *any* nodes, e.g. your neighbors in the local network, while peer routing is about finding addresses for *specific* nodes.

**Comment by diasdavid** [comment]
@plintx see these tutorials, they walk you through different properties and how to use them:

- https://github.com/libp2p/js-libp2p/tree/master/examples/discovery-mechanisms
- https://github.com/libp2p/js-libp2p/tree/master/examples/peer-and-content-routing

**Comment by mxinden** [comment]
Closing here. Feel free to open another issue to continue this discussion.
