### ISSUE TITLE
typo in circuit-v2 doc

### ISSUE THREAD

**Issue by gitaaron** [libp2p/specs#378]
~~r/sgtatus/status on this [line](https://github.com/libp2p/specs/blob/c541d2cd92e2243bfbaca308e56f75d1d4a64552/relay/circuit-v2.md?plain=1#L279)~~  ( not an issue anymore I was looking at the wrong branch )

r/two/too on this [line](https://github.com/libp2p/specs/blob/c541d2cd92e2243bfbaca308e56f75d1d4a64552/relay/circuit-v2.md?plain=1#L292)

**Comment by mxinden** [comment]
Good catch. Mind creating a pull request @gitaaron?
