### ISSUE TITLE
pubsub: consider single required topic hash

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/specs#399]
Currently, rust-libp2p assumes a single required topic hash (https://github.com/libp2p/rust-libp2p/blob/a168410dbed0d0941f2e5a14543206044ccb2260/protocols/gossipsub/src/types.rs#L123)

This simplifies the code a lot and seems to be the standard use-case for pubsub protocols.

Perhaps this can be applied at the spec level and rolled out to other implementations.

cc @dapplion

**Comment by vyzo** [comment]
No, we've had this discussion before -- we are not changing the spec to require hashes.

Note that messages have a single topic for a while now, if that's what you mean; the spec might need to be updated for that.

**Comment by vyzo** [comment]
we changed the protobuf too in go pubsub, but backwards compatible (same field id).

Mind opening a pr to update the spec?

**Comment by wemeetagain** [comment]
> Mind opening a pr to update the spec?

Sure thing

**Comment by mxinden** [comment]
If I am not mistaken this can be closed with https://github.com/libp2p/specs/pull/400.
