### ISSUE TITLE
What is E_DIAL_REFUSED for in autonat?

### ISSUE THREAD

**Issue by achingbrain** [libp2p/specs#427]
The autonat protocol contains a `E_DIAL_REFUSED` status but it's not mentioned anywhere in the spec body.

When would you send it or expect to receive it?

**Comment by MarcoPolo** [comment]
I believe it is for when the other end refused to dial the given address (didn’t make an attempt) vs it dialed and errored. There are a couple reasons why it would refuse, I think the spec mentions a couple but it’s probably not exhaustive.

I think it makes sense to add this to the spec. 

A related issue here: https://github.com/libp2p/specs/issues/411

**Comment by achingbrain** [comment]
Ok, great - I was looking for the case where you tell me to dial an address on a transport that I don't support, I shouldn't tell you it errored, I should tell you I can't help out and you should ask someone else.  Sounds like this is it.

I'll PR the spec to add this.

**Comment by achingbrain** [comment]
PR is here: https://github.com/libp2p/specs/pull/430
