### ISSUE TITLE
Include test vectors in specifications

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/specs#459]
Whilst reviewing the `rust-libp2p` implementation of the QUIC transport, I took a closer look at the TLS specification: https://github.com/libp2p/specs/blob/master/tls/tls.md

What do people think about including test vectors in there? I am thinking something like:

- Given ed25519 identity keypair X
- Given certificate keypair
- A valid certificate with the custom libp2p protocol extension looks like XYZ

This would make it possible to easily write unit tests against this fairly critical part of the code and would potentially catch interoperability issues early on.

**Comment by marten-seemann** [comment]
Sounds like a good idea. Want to create a PR? I’d create a test case for go-libp2p as part of reviewing that PR.

**Comment by thomaseizinger** [comment]
I'll see to put some test vectors together from the current Rust implementation!

**Comment by thomaseizinger** [comment]
This is proving trickier than I thought it would. Creating test vectors for parsing a certificate is easy but generation is difficult because the ECDSA signature of the certificate itself incorporates randomness.

**Comment by thomaseizinger** [comment]
I guess parsing could be enough? Implementations can always write round-trip tests where they try to parse their own certificates. If that passes, generation should be okay too!

**Comment by thomaseizinger** [comment]
I am adding tests with a static inputs in https://github.com/libp2p/rust-libp2p/pull/2945.

Here is a direct link: https://github.com/libp2p/rust-libp2p/blob/3b76e39c68192318111fd9142df5a79f281c3bf6/transports/tls/src/certificate.rs#L497-L544

Do you want to test these against the go implementation? Once successful, I can PR them to the spec.
