### ISSUE TITLE
Censorship-resistant transports

### ISSUE THREAD

**Issue by planetoryd** [libp2p/specs#480]
- would be useful along with #472 
  - turn all relays into bridges like how i2p does with ssu2
- obfs4 is reportedly detectable by GFW
- alternatives: shadowtls, naiveproxy, ssu2

**Comment by TheRook** [comment]
Tor doesn't help with censorship resistance. Tor is filtered, and you need a first party solution to help connect nodes that are behind an IP address blacklist.
