### ISSUE TITLE
Transport Compression

### ISSUE THREAD

**Issue by Winterhuman** [libp2p/specs#485]
I recently saw this project (https://github.com/individe/js-libp2p-snappy-muxer) and was reminded about an issue related to this, but it turns out the issue is at https://github.com/libp2p/libp2p/issues/81. I'm opening this issue to maybe revitalize interest in transport-level compression

**Comment by mxinden** [comment]
I am not aware of any recent, ongoing or planned efforts for compression on the transport layer. This is not to say that we should never do it.

**Comment by jclab-joseph** [comment]
Why is this Issue closed?
Wouldn't something like lz4/zstd help?
I'm interested in reducing traffic when sharing files using IPFS.

**Comment by marten-seemann** [comment]
There's no benefit whatsoever to doing compression **at the transport layer**. This can equally well be done at the application layer.
