### ISSUE TITLE
[Doc] Update required for outdated link in libp2p TLS Handshake (specs/tls/tls.md)

### ISSUE THREAD

**Issue by MuhtasimTanmoy** [libp2p/specs#510]
This doc [specs/tls/tls.md](https://github.com/libp2p/specs/blob/master/tls/tls.md) contains an outdated link in the following section.

> Certificates MUST use the NamedCurve encoding for elliptic curve parameters. Endpoints MUST abort the connection attempt if is not used. Failure to enforce this restriction allows [“Whose Curve Is It Anyway”](https://whosecurve.com/) attacks, which completely compromise the security of the connection. Similarly, hash functions with an output length less than 256 bits MUST NOT be used, due to the possibility of collision attacks. In particular, MD5 and SHA1 MUST NOT be used.

Does it needs to be updated with [link from web archive](https://web.archive.org/web/20201027175628/https://whosecurve.com) or should be removed?

**Comment by mxinden** [comment]
I wonder whether this paragraph is still relevant in the first place. I would expect patches to be widely deployed by now.

I would assume @marten-seemann is way more knowledgeable here. Any thoughts?

**Comment by marten-seemann** [comment]
This was added in https://github.com/libp2p/specs/pull/255. I don't have any strong opinions, this is something that I trust my TLS stack to handle for me :)
I'd be ok with removing this paragraph.

**Comment by mxinden** [comment]
@MuhtasimTanmoy would you mind opening a pull request removing the paragraph?
