### ISSUE TITLE
docs: WebTransport and CircuitV2

### ISSUE THREAD

**Issue by Winterhuman** [libp2p/specs#523]
I was reading https://github.com/libp2p/specs/tree/master/webtransport when I saw:

"The WebTransport URL of a WebTransport server advertising /ip4/192.0.2.0/udp/1443/quic/webtransport/ would be https://192.0.2.0:1443/.well-known/libp2p-webtransport?type=noise."

If the URL is what's actually being tried, doesn't that mean you can't use WebTransport only with CircuitV2 to establish a connection from a browser to a node behind NAT? Should this be documented if so?

**Comment by marten-seemann** [comment]
WebTransport runs on top of HTTP/3, so there's no way around this.

**Comment by Winterhuman** [comment]
Thanks for confirming. Do you think it's worth noting somewhere in the documentation that HTTP-based transport are incompatible with CircuitV2?

**Comment by marten-seemann** [comment]
That applies to all non-TCP transports, doesn't it?

**Comment by Winterhuman** [comment]
QUIC & WebRTC work don't they?

**Comment by Winterhuman** [comment]
Ah no, WebSocket wouldn't either since that needs a URL too

**Comment by Winterhuman** [comment]
I see what you mean now, anything that isn't TCP or QUIC is incompatible with CircuitV2, there would be too many transports to list them all; it's an inherit property of web-available transports. Closing issue

**Comment by marten-seemann** [comment]
A relayed connection is a single, bidirectional byte stream, so all you can is upgrade that byte stream with a security and muxer protocol, analogous to what you do with a TCP connection.

For the connection to the relay, you can use any transport you like, including WebRTC and WebTransport.

**Comment by marten-seemann** [comment]
Circuitv2 doesn't allow direct connection, it allows relayed connections. It is a prerequisite for hole punching though, which _then_ would give you a direct connection.

This should answer you question:
> For the connection to the relay, you can use any transport you like, including WebRTC and WebTransport.

**Comment by Winterhuman** [comment]
No, I'm still confused, you're saying CircuitV2 can give you a direct connection after the holepunching packets are sent, but you also said "WebTransport runs on top of HTTP/3, so there's no way around this." implying WebTransport can't use the holepunched ports?

I'll leave the discussion here though, it's better if I wait until CircuitV2 support is merged in js-libp2p to actually test this
