### ISSUE TITLE
Add test vectors for encoding and decoding keypairs

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/specs#533]
We support encoding and decoding keys in [various formats](https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md#key-types) but there is not standardized test-suite that implementations can test against.

We should fix that by providing at least one test vector for each key type.

**Comment by marten-seemann** [comment]
Sounds reasonable. Want to send a PR? Happy to do cross-check with go-libp2p.

**Comment by thomaseizinger** [comment]
What would be the best way here?

We can provide hex-encoded, serialised protobuf for each private key and public key. That covers the decoding bit. Is there any way we can cover the encoding bit?

**Comment by marten-seemann** [comment]
Why does this not cover the encoding part, if we also provide the hex-encoded private key?

**Comment by thomaseizinger** [comment]
> Why does this not cover the encoding part, if we also provide the hex-encoded private key?

Because technically, that is extending the spec that we should also support decoding a private key from hex.

The crypto library we use for RSA for example doesn't even allow us to initalise a private key from just the secret exponent (for security reasons I presume). I can imagine other languages have similar restrictions.

I guess what we could do is tell implementations to add a decode-encode roundtrip test. That, together with some tests for verifying signatures should make sure the key is parsed correctly and can also be encoded again.
