### ISSUE TITLE
Reporting the listening and observed addresses should be done separately

### ISSUE THREAD

**Issue by tomaka** [libp2p/specs#55]
Right now dialing a node and upgrading with `identify` will make the node return the observed address of the dialer, plus the listening address of the listener.

However in practice, because of NAT traversal, in order to report the address it's listening on, a server needs to know how it's being perceived by the outside.
This introduces the possibility of a cyclic dependency if two nodes try to identify each other.

Separating the observed address from the listening address would make the whole system cleaner in my opinion.

**Comment by mxinden** [comment]
@tomaka do I understand correctly that you are suggesting a change similar to the below?

```diff
  message Identify {
    optional string protocolVersion = 5;
    optional string agentVersion = 6;
    optional bytes publicKey = 1;
-   repeated bytes listenAddrs = 2;
+   repeated bytes listenAddrsListener = 2;
+   repeated bytes observedAddrsListener = 7;
-   optional bytes observedAddr = 4;
+   optional bytes observedAddrDialer = 4;
    repeated string protocols = 3;
  }

```

**Comment by tomaka** [comment]
If I remember correctly, I was thinking of splitting off the message in two separate messages: one for the listened addresses and one for the observed addresses.
Nodes would first exchange the observed address of each other, then exchange their listened addresses.

I don't think it's a critical problem.

**Comment by mxinden** [comment]
Got it, thanks for clarifying! I assume that the status quo is good enough. I will close here. Let's revive this discussion in case someone would like to pick it up again.
