### ISSUE TITLE
Feature Request: mdns in libp2p

### ISSUE THREAD

**Issue by remmerw** [libp2p/specs#572]
The current implementation of mDNS in libp2p (go) publish a set of multi addresses.
The multi addresses are not encoded and probably consume more bytes then an encoded version (like the addresses in identity proto)
Does it make sense to publish the identity instead of publishing the plain multi address?
Nice benefit would be, that the peers protocols are known before dialing the peer.

**Comment by thomaseizinger** [comment]
mDNS packets have a size limit so we need to take that into account. Overall, I'd say this sounds like a new spec to me rather than changing the existing one.

mDNS is cool but ultimately a not very important discovery mechanism IMO. It would be more useful to push things like https://github.com/libp2p/specs/issues/498 forward which allows all connections to benefit from decreased latency until they receive the identify info.

**Comment by marten-seemann** [comment]
Reducing the handshake latency is not really interesting on local networks, since the RTT is so small anyway. It matters much more on the public internet.

**Comment by thomaseizinger** [comment]
> Reducing the handshake latency is not really interesting on local networks, since the RTT is so small anyway.

Right, that leads us to the same conclusion though :)
Optimising mDNS to include identify info isn't really worth it because it only works on local networks so you might as well just do another RT and fetch identify regularly.

**Comment by marten-seemann** [comment]
@thomaseizinger I agree with you, I was just adding to your point :)

**Comment by remmerw** [comment]
I try to understand the proposal https://github.com/libp2p/specs/issues/498
.
Is it a requirement for use the early data feature to had an existing connection before, so that early data is possible?
Probably not the forum to ask questions. Feel free to close the entry. I got my answer.

**Comment by marten-seemann** [comment]
> Is it a requirement for use the early data feature to had an existing connection before, so that early data is possible?

It is not. It's all explained in #498 (0.5-RTT section).

Closing this issue here since there's nothing actionable.
