### ISSUE TITLE
JAVA interface

### ISSUE THREAD

**Issue by Srivatsa-M-Hegde** [libp2p/specs#65]
I am a student trying to implement the bitswap module in java. My current understanding is the Kademlia DHT features are provided by the libp2p. Is there any interface that I could use  the libp2p library with to make my bitswap implementation in java leverage this library ?

**Comment by jacobheun** [comment]
The [go-libp2p-daemon](https://github.com/libp2p/go-libp2p-daemon) is currently under development to allow for other languages to interact with the libp2p node. This would enable you to control the existing node, including the DHT, via Java.

**Comment by mxinden** [comment]
I am closing here. @Srivatsa-M-Hegde feel free to make a follow-up comment in case you have further questions.
