### ISSUE TITLE
GossipSub: GetNodes message handling

### ISSUE THREAD

**Issue by jannikluhn** [libp2p/specs#81]
In the [Joining the Overlay](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub#joining-the-overlay) section of the GossipSub specification a `GETNODES` message type is mentioned, but not how receivers should handle it. My guess is that they should respond with a `NODES` message containing a subset of their active and/or passive list. Is that correct? If so, what's the point of the `ttl` field in the `NODES` message?

**Comment by whyrusleeping** [comment]
Hey @jannikluhn, sorry for the delay. Been a busy couple of weeks. I'll get this and your other question answered soon!

**Comment by vyzo** [comment]
Ok, I think there is some confusion here -- the gossipsub spec that got checked in doesn't correspond to the protocol implementation. 
Rather, it is based on an earlier proposal for epidemic proximity aware pubsub, which is planned for the next iteration of the protocol.

**Comment by raulk** [comment]
This misrepresentation got fixed with #84.
