### ISSUE TITLE
GossipSub: Neighbor message

### ISSUE THREAD

**Issue by jannikluhn** [libp2p/specs#82]
The GossipSub spec defines a `NEIGHBOR` message with a `peers` field. It is used for

- accepting `JOIN` requests
- requesting connections to near neighbors
- accepting a neighbor request

But for none of these any other nodes than sender and receiver seem to be necessary. So what's the point of `peers` and how is it used?

**Comment by mhchia** [comment]
cc @whyrusleeping @vyzo

**Comment by mxinden** [comment]
As far as I can tell, this question is obsolete with the recent GossipSub changes. @jannikluhn please follow up here in case you still need help.
