### ISSUE TITLE
Protobuf files

### ISSUE THREAD

**Issue by jamesray1** [libp2p/specs#88]
`.proto` files should be included as part of the specs, since all implementations need to use the same file for compatibility.

**Comment by mxinden** [comment]
Today most protocols have their Protoobuf definitions defined in the specs themselves. Unless we find a way to keep the two in sync I am not keen on adding an additional source of truth.

Given the lack of progress on this issue I am closing it. In case someone would like to continue the discussion or pick this issue up as a work item, please leave a comment.
